name: Build and deploy to production

on: 
  push:
    branches: 
      - dev
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
      
      
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: fastapicd.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
     
     
    - name: Build and push container image to registry 
      run: |
        docker build . -t udaapi.azurecr.io/uml-extractor-api:${{ github.sha }} --build-arg MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} --build-arg MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} --build-arg MAIL_SERVER=${{ secrets.MAIL_SERVER }} --build-arg ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }} --build-arg ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}
        docker push udaapi.azurecr.io/uml-extractor-api:${{ github.sha }}
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastapi-cd'
        images: 'udaapi.azurecr.io/uml-extractor-api:${{ github.sha }}'
        
        
    - name: Azure logout
      run: |
        az logout
